---
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Install MySQL server
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password"
        value: "{{ mysql_root_password }}"
        vtype: "password"

    - name: Confirm MySQL root password again
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password_again"
        value: "{{ mysql_root_password }}"
        vtype: "password"

    - name: Install MySQL package
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL is running
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Install PHP and required modules
      apt:
        name: "{{ php_packages }}"
        state: present

    - name: Restart Apache to load PHP
      systemd:
        name: apache2
        state: restarted

    - name: PHP info page
      copy:
        dest: /var/www/html/info.php
        content: "<?php phpinfo(); ?>"
        mode: '0644'

    - name: Download CloudWatch Agent package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb

    - name: Install CloudWatch Agent
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb

    - name: Create CloudWatch Agent config directory
      file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: '0755'

    - name: Upload CloudWatch Agent configuration file
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "root"
            },
            "metrics": {
              "namespace": "CWAgent",
              "append_dimensions": {
                "InstanceId": "${aws:InstanceId}"
              },
              "metrics_collected": {
                "cpu": {
                  "measurement": [
                    "cpu_usage_idle",
                    "cpu_usage_user",
                    "cpu_usage_system"
                  ],
                  "metrics_collection_interval": 60,
                  "totalcpu": true
                },
                "mem": {
                  "measurement": [
                    "mem_used_percent"
                  ],
                  "metrics_collection_interval": 60
                },
                "disk": {
                  "measurement": [
                    "disk_used_percent"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "/"
                  ]
                }
              }
            }
          }

    - name: Start CloudWatch Agent
      command: >
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config
        -m ec2
        -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        -s