---
- name: Ensure Nginx is installed and running
  hosts: all
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Ensure Nginx is at the latest version
      apt:
        name: nginx
        state: latest

    - name: Make sure Nginx is running
      systemd:
        name: nginx
        state: started






##rename this file to lamp and even folder since that's what will be installed and keep by the end; not nginx 